language: node_js

node_js:
  - '0.10'

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - REPORTER=Dot
  matrix:
    - BUNDLE="ember=1.2.2&jQuery=1.10.2&handlebars=1.3.0"
    - BUNDLE="ember=1.2.2&jQuery=2.0.3&handlebars=1.3.0"
    - BUNDLE="ember=1.3.2&jQuery=1.10.2&handlebars=1.3.0"
    - BUNDLE="ember=1.3.2&jQuery=2.0.3&handlebars=1.3.0"
    - BUNDLE="ember=1.4.0&jQuery=1.11.2&handlebars=1.3.0"
    - BUNDLE="ember=1.4.0&jQuery=2.1.3&handlebars=1.3.0"
    - BUNDLE="ember=1.5.1&jQuery=1.11.2&handlebars=1.3.0"
    - BUNDLE="ember=1.5.1&jQuery=2.1.3&handlebars=1.3.0"
    - BUNDLE="ember=1.6.1&jQuery=1.11.2&handlebars=1.3.0"
    - BUNDLE="ember=1.6.1&jQuery=2.1.3&handlebars=1.3.0"
    - BUNDLE="ember=1.7.1&jQuery=1.11.2&handlebars=1.3.0"
    - BUNDLE="ember=1.7.1&jQuery=2.1.3&handlebars=1.3.0"
    - BUNDLE="ember=1.8.1&jQuery=1.11.2&handlebars=1.3.0"
    - BUNDLE="ember=1.8.1&jQuery=2.1.3&handlebars=1.3.0"
    - BUNDLE="ember=1.9.1&jQuery=1.11.2&handlebars=2.0.0"
    - BUNDLE="ember=1.9.1&jQuery=2.1.3&handlebars=2.0.0"
    - BUNDLE="ember=1.10.0&jQuery=1.11.2&handlebars=2.0.0"
    - BUNDLE="ember=1.10.0&jQuery=2.1.3&handlebars=2.0.0"

notifications:
  email:
    on_success: never
